### ISSUE TITLE
log retention is supported in every plan

### ISSUE THREAD

**Issue by huikang** [IBM-Bluemix-Docs/CloudLogAnalysis#3]
Looks like every plan supports log retention.

https://github.com/IBM-Bluemix-Docs/CloudLogAnalysis/blob/master/manage_logs.md#managing-logs

**Comment by lopezdsr** [comment]
Only premium plans (paid plans) support long term long retention.
The documentation specifies that  "This feature is only available for service plans that allow log retention."
