### ISSUE TITLE
No DevOps category

### ISSUE THREAD

**Issue by bennythejudge** [IBM-Bluemix-Docs/CloudLogAnalysis#4]
@lopezdsr 
I am following https://console.bluemix.net/docs/services/CloudLogAnalysis/how-to/provision.html#provision and step 3 (provisioning from the UI) reads:

```
Select the DevOps category to filter the list of services that is displayed.
```

I do not see a DevOps category

![screen shot 2018-08-22 at 10 15 40](https://user-images.githubusercontent.com/7428118/44451732-d8a38b00-a5f4-11e8-9182-f4a56ef24f97.png)

Log Analyses is under "Developer Tools".

**Comment by lopezdsr** [comment]
Thank you very much for the feedback. I have fixed the error.
